manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: timception
      url-base: https://github.com/timception
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml
    - name: zmk-behavior-key-press-lip
      remote: timception
      revision: main
  self:
    path: config
